### ISSUE TITLE
convert_keras.py raise AssertionError using mnist example with complex model

### ISSUE THREAD

**Issue by knok** [mil-tokyo/webdnn#495] opened 2017-08-31 00:31 UTC
```
python train_mnist_keras.py --model complex
Converting model into WebDNN format (graph descriptor)
$ python ../../bin/convert_keras.py output_keras/./keras_model/complex.h5 --backend webgpu,webgl,webassembly,fallback --input_shape '('1', 28, 28, 1)' --out output_keras
Using TensorFlow backend.
[convert_keras.py] Generating feedforward graph
(snip)
[convert_keras.py] Generating graph descriptor
[convert_keras.py] BackendName: webgpu
/opt/p36/lib/python3.6/site-packages/webdnn-1.1.0-py3.6.egg/webdnn/util/console.py:27: Warning: [WebGPUDescriptorGenerator] 'xcrun' command is not found. validation of generated source code in webgpu backend is skipped.
  warnings.warn(message, category)
[convert_keras.py] BackendName: webgl
[convert_keras.py] BackendName: webassembly
[convert_keras.py] BackendName: fallback
[convert_keras.py] Failed generating descriptor for fallback backend
Traceback (most recent call last):
  File "../../bin/convert_keras.py", line 96, in main
    graph_exec_data = generate_descriptor(backend, graph, constant_encoder_name=args.encoding)
  File "/opt/p36/lib/python3.6/site-packages/webdnn-1.1.0-py3.6.egg/webdnn/backend/interface/generator.py", line 99, in generate_descriptor
    return generator(graph, **kwargs)
  File "/opt/p36/lib/python3.6/site-packages/webdnn-1.1.0-py3.6.egg/webdnn/backend/fallback/generator.py", line 75, in generate
    return FallbackDescriptorGenerator.generate(graph, **kwargs)
  File "/opt/p36/lib/python3.6/site-packages/webdnn-1.1.0-py3.6.egg/webdnn/backend/fallback/generator.py", line 64, in generate
    kernels=cls.generate_kernels(graph, memory_layout),
  File "/opt/p36/lib/python3.6/site-packages/webdnn-1.1.0-py3.6.egg/webdnn/backend/interface/generator.py", line 51, in generate_kernels
  File "/opt/p36/lib/python3.6/site-packages/webdnn-1.1.0-py3.6.egg/webdnn/backend/fallback/kernels/softmax.py", line 49, in softmax
    assert y.order == x.order
AssertionError

Traceback (most recent call last):
  File "train_mnist_keras.py", line 209, in <module>
    main()
  File "train_mnist_keras.py", line 205, in main
    convert(args.backend, model_path, _get_input_shape(args.model), args.out)
  File "train_mnist_keras.py", line 187, in convert
    subprocess.check_call(convert_keras_command, shell=True)
  File "/home/knok/.pyenv/versions/3.6.2/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'python ../../bin/convert_keras.py output_keras/./keras_model/complex.h5 --backend webgpu,webgl,webassembly,fallback --input_shape '('1', 28, 28, 1)' --out output_keras' returned non-zero exit status 1.
```

It seems to work all of backends except fallback.
The another models (fc, conv, dilated_conv and residual) are work fine.

**Comment by milhidaka** [comment] 2017-09-01 09:22
Thanks for reporting.
The problem is now fixed. #500

**Closed** 2017-09-01 09:21 UTC
